-- ============================================
-- FINAL REPORT DRAFTS TABLE
-- ============================================
-- This table stores server-side drafts for final reports.
-- Field officers, desk officers, chiefs, and admins can all
-- edit drafts before publishing to final_reports.

CREATE TABLE IF NOT EXISTS public.final_report_drafts (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incident_id uuid NOT NULL UNIQUE REFERENCES public.incidents(id) ON DELETE CASCADE,
  agency_type text NOT NULL CHECK (agency_type = ANY (ARRAY['pnp'::text, 'bfp'::text, 'pdrrmo'::text])),
  author_id uuid REFERENCES public.profiles(id),
  draft_details jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'draft' CHECK (status = ANY (ARRAY['draft'::text, 'ready_for_review'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Index for fast lookups by incident
CREATE INDEX IF NOT EXISTS idx_final_report_drafts_incident_id ON public.final_report_drafts(incident_id);

-- Index for filtering by agency
CREATE INDEX IF NOT EXISTS idx_final_report_drafts_agency_type ON public.final_report_drafts(agency_type);

-- Index for filtering by status
CREATE INDEX IF NOT EXISTS idx_final_report_drafts_status ON public.final_report_drafts(status);

-- ============================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================
-- Enable RLS
ALTER TABLE public.final_report_drafts ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view drafts for incidents they have access to
-- (Field officers see their assigned incidents, chiefs/admins see their agency/station)
CREATE POLICY "Users can view drafts for accessible incidents"
  ON public.final_report_drafts
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.incidents i
      WHERE i.id = final_report_drafts.incident_id
      AND (
        -- Admin can see all
        EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'Admin')
        OR
        -- Field officer assigned to incident
        i.assigned_officer_id = auth.uid()
        OR
        auth.uid() = ANY(i.assigned_officer_ids)
        OR
        -- Chief/Desk Officer at assigned station
        EXISTS (
          SELECT 1 FROM public.profiles p
          WHERE p.id = auth.uid()
          AND p.role IN ('Chief', 'Desk Officer')
          AND p.station_id = i.assigned_station_id
        )
      )
    )
  );

-- Policy: Users can insert drafts for incidents they have access to
CREATE POLICY "Users can create drafts for accessible incidents"
  ON public.final_report_drafts
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.incidents i
      WHERE i.id = final_report_drafts.incident_id
      AND (
        EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'Admin')
        OR
        i.assigned_officer_id = auth.uid()
        OR
        auth.uid() = ANY(i.assigned_officer_ids)
        OR
        EXISTS (
          SELECT 1 FROM public.profiles p
          WHERE p.id = auth.uid()
          AND p.role IN ('Chief', 'Desk Officer')
          AND p.station_id = i.assigned_station_id
        )
      )
    )
  );

-- Policy: Users can update drafts for incidents they have access to
CREATE POLICY "Users can update drafts for accessible incidents"
  ON public.final_report_drafts
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.incidents i
      WHERE i.id = final_report_drafts.incident_id
      AND (
        EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'Admin')
        OR
        i.assigned_officer_id = auth.uid()
        OR
        auth.uid() = ANY(i.assigned_officer_ids)
        OR
        EXISTS (
          SELECT 1 FROM public.profiles p
          WHERE p.id = auth.uid()
          AND p.role IN ('Chief', 'Desk Officer')
          AND p.station_id = i.assigned_station_id
        )
      )
    )
  );

-- Policy: Only Admin/Chief can delete drafts
CREATE POLICY "Admin and Chief can delete drafts"
  ON public.final_report_drafts
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid()
      AND p.role IN ('Admin', 'Chief')
    )
  );

-- ============================================
-- TRIGGER: Auto-update updated_at
-- ============================================
CREATE OR REPLACE FUNCTION update_final_report_drafts_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_final_report_drafts_updated_at
  BEFORE UPDATE ON public.final_report_drafts
  FOR EACH ROW
  EXECUTE FUNCTION update_final_report_drafts_updated_at();

-- ============================================
-- COMMENTS
-- ============================================
COMMENT ON TABLE public.final_report_drafts IS 'Server-side drafts for final reports, editable by field officers, desk officers, chiefs, and admins';
COMMENT ON COLUMN public.final_report_drafts.draft_details IS 'JSONB containing agency-specific form fields (same structure as final_reports.report_details)';
COMMENT ON COLUMN public.final_report_drafts.status IS 'draft = work in progress, ready_for_review = submitted for approval';
